### ISSUE TITLE
[1.20.1] Crash when moving stuff in inventory

### ISSUE THREAD

**Issue by FoxMcloud5655** [Sonmok14/FromTheShadows#2]
This is quite the weird bug, but it seems to be a combination of Patchouli and From The Shadows causing this error.  All versions are the latest as of this post; exact versions can be requested if needed.  This may be a Patchouli bug, but my intuition tells me it's not.
```
Description: Rendering screen

java.lang.RuntimeException: Unknown item ID: fromtheshadows:apocrypha
	at vazkii.patchouli.common.util.ItemStackUtil.loadFromParsed(ItemStackUtil.java:77) ~[Patchouli-1.20.1-81-FORGE.jar%23588!/:1.20.1-81-FORGE] {re:classloading}
	at vazkii.patchouli.common.book.Book.lambda$new$1(Book.java:162) ~[Patchouli-1.20.1-81-FORGE.jar%23588!/:1.20.1-81-FORGE] {re:mixin,re:classloading}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?] {}
	at vazkii.patchouli.common.book.Book.getBookItem(Book.java:174) ~[Patchouli-1.20.1-81-FORGE.jar%23588!/:1.20.1-81-FORGE] {re:mixin,re:classloading}
	at vazkii.patchouli.common.util.ItemStackUtil.getBookFromStack(ItemStackUtil.java:122) ~[Patchouli-1.20.1-81-FORGE.jar%23588!/:1.20.1-81-FORGE] {re:classloading}
	at vazkii.patchouli.client.handler.TooltipHandler.onTooltip(TooltipHandler.java:44) ~[Patchouli-1.20.1-81-FORGE.jar%23588!/:1.20.1-81-FORGE] {re:classloading}
	at vazkii.patchouli.forge.client.ForgeClientInitializer.lambda$onInitializeClient$12(ForgeClientInitializer.java:147) ~[Patchouli-1.20.1-81-FORGE.jar%23588!/:1.20.1-81-FORGE] {re:classloading}
```

**Comment by Sonmok14** [comment]
fixed version will be uploaded soon sry ;-;
