### ISSUE TITLE
Process ended with exit code 0

### ISSUE THREAD

**Issue by B-Wither** [Sonmok14/FromTheShadows#9]
Just tested for my pack, and it crashed when loaded this mod, without crash report.

16:16:27.528
net.minecraft.client.Minecraft
Render thread
Shutdown failure!
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.forEach(HashMap.java:1424)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.texture.TextureManager.close(TextureManager.java:178)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.close(Minecraft.java:1070)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91393_(Minecraft.java:1043)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:234)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
16:16:28.187
launcher
main

16:16:28.187
monitor
Process Monitor
Process ended with exit code 0

![image](https://github.com/Sonmok14/FromTheShadows/assets/63962480/7ddb6df7-a7ed-4843-988e-7201dfed7c0f)
![image](https://github.com/Sonmok14/FromTheShadows/assets/63962480/66ac226d-8890-4dd5-906f-67104818fb6b)

**Comment by B-Wither** [comment]
If I remove Artifacts mod, then it shows like this.
![image](https://github.com/Sonmok14/FromTheShadows/assets/63962480/5e7d0508-e42c-41cb-b6cc-ff75730aa2d9)

**Comment by B-Wither** [comment]
[crash-2023-09-09_18.00.08-client.txt](https://github.com/Sonmok14/FromTheShadows/files/12565359/crash-2023-09-09_18.00.08-client.txt)
Updated Forge to 47.1.3, and changed some mods, then crash report generated.

**Comment by Sonmok14** [comment]
https://www.curseforge.com/minecraft/mc-mods/geckolib

**Comment by B-Wither** [comment]
Thank you!
